package com.example;

import java.io.*;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
@Retention(RetentionPolicy.RUNTIME)
@interface Template {
    String generatedHTML() default  "<h1>This was generated by annotation</h1>" +
            "<p>This is a placeholder for the route since no method was implemented.</p>";
}

@Template
class PlaceholderTemplate extends HttpServlet {
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        response.setContentType("text/html");
        PrintWriter pw = response.getWriter();
        Class<?> clazz = PlaceholderTemplate.class;
        Template ann = clazz.getAnnotation(Template.class);
        pw.println(ann.generatedHTML());
        pw.close();
    }
}

//@WebServlet(name = "HelloServlet", urlPatterns = {"/hello"})
public class HelloServlet extends PlaceholderTemplate {
//    @Override
//    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
//        response.setContentType("text/html");
//        PrintWriter pw = response.getWriter();
//        pw.println("<b>Hello!</b>");
//        pw.close();
//    }
}
